version: "3"

services:
  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    environment:
      - DYN_FLAG=AKCTF25{j1nj4_0wn3d_4g41n}
      - FLASK_APP=app.py
      - FLASK_ENV=development
    command: python app.py
