FROM nginx:latest
COPY nginx.conf /etc/nginx/conf.d/default.conf
COPY index.html /usr/share/nginx/html/index.html
COPY robots.txt /usr/share/nginx/html/robots.txt
COPY secret-flag.txt /usr/share/nginx/html/seee3333cccrrr333ttttffllll44ggg.txt
